services:

  blaubot:
    image: bluefireoly/blaubot:latest
    restart: unless-stopped
    volumes:
      - ./config:/app/config/

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 120
